# Contains the files to be produced 
source_dir = "/path/to/source"

# Where the producer drops files 
destination_dir = "/path/to/destination"

# Number of files dropped each time the producer runs
batch_size = 1

# Delay between drops 
interval = 2s
